site_name: Hướng dẫn sử dụng hệ thống vContract

nav:
  - "Trang chủ": "index.md"
  - "vContract - Hợp đồng điện tử":
      - "Cấu hình trước khi sử dụng": "vContract/cau-hinh-truoc-khi-su-dung.md"
      - "Thao tác trên hợp đồng": "vContract/thao-tac-tren-hop-dong.md"
  - "Release Notes": "release-notes.md"
theme:
  name: readthedocs
  navigation_depth: 100
  highlightjs: true
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
copyright: Prepared by <a href="https://hopdongdientu.viettel.vn/">vContract - Viettel.</a>
